In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [4]:
df.corr(numeric_only=True)

                   year  selling_price  km_driven
year           1.000000       0.413922  -0.419688
selling_price  0.413922       1.000000  -0.192289
km_driven     -0.419688      -0.192289   1.000000

In [5]:
x = df[['km_driven']]
y = df['selling_price']

In [6]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
lr.fit(x_train,y_train)

LinearRegression()

In [8]:
y_pred = lr.predict(x_test)

In [9]:
for i,j in zip(y,y_pred):
    print(i,'-->',j)

60000 --> 474691.6518469233
135000 --> 600033.791712637
600000 --> 565214.6912363558
250000 --> 330429.94369959243
450000 --> 521990.5725509662
140000 --> 618771.2591495435
550000 --> 630134.8248486898
240000 --> 604763.6837830412
850000 --> 569289.4932550091
365000 --> 564559.6011846048
260000 --> 526720.4646213704
250000 --> 545640.0329029877
1650000 --> 545640.0329029877
60000 --> 389553.5945796461
135000 --> 618700.3107684875
600000 --> 642222.064034608
250000 --> 629167.5619202922
450000 --> 427392.7311428804
140000 --> 498341.1121989447
550000 --> 455772.08356530615
240000 --> 521990.5725509662
850000 --> 545640.0329029877
365000 --> 581114.2234310198
260000 --> 592938.9536070304
250000 --> 474691.6518469233
1650000 --> 545640.0329029877
585000 --> 458137.0296005083
1195000 --> 498341.1121989447
390000 --> 545640.0329029877
1964999 --> 654427.5505222862
1425000 --> 498341.1121989447
975000 --> 628413.1441350627
1190000 --> 491246.2740933383
930000 --> 595303.8996422327
525000 --> 604763.6837830412
1735000 --> 403743.27079085895
1375000 --> 628413.1441350627
450000 --> 604763.6837830412
900000 --> 474691.6518469233
1300000 --> 654427.5505222862
1400000 --> 474691.6518469233
850000 --> 601216.264730238
229999 --> 569289.4932550091
1550000 --> 370634.02629802894
1250000 --> 451042.19149490184
625000 --> 427392.7311428804
1050000 --> 609493.5758534456
560000 --> 356444.35008681606
290000 --> 498341.1121989447
275000 --> 469961.759776519
411000 --> 299685.6452419646
150000 --> 569289.4932550091
500000 --> 533011.2210750082
100000 --> 545640.0329029877
725000 --> 574019.3853254133
401000 --> 518242.13308517076
750000 --> 474691.6518469233
310000 --> 235832.10229150666
665000 --> 656224.9095090398
465000 --> 590384.8118890122
160000 --> 498341.1121989447
250000 --> 380093.8104388375
675000 --> 616588.413959052
300000 --> 465231.86770611466
70000 --> 474691.6518469233
240000 --> 581114.2234310198
525000 --> 533011.2210750082
151000 --> 539642.529757715
140000 --> 380093.8104388375
280000 --> 498341.1121989447
350000 --> 592938.9536070304
570000 --> 616588.413959052
300000 --> 427392.7311428804
100000 --> 498341.1121989447
500000 --> 474691.6518469233
125000 --> 559829.7091142004
130000 --> 119949.74656660156
925000 --> 553900.7894039487
750000 --> 557464.7630789983
200000 --> 474712.9363612401
248000 --> 498341.1121989447
450000 --> 498341.1121989447
80000 --> 521990.5725509662
650000 --> 617534.3923731328
450000 --> 498341.1121989447
650000 --> 332794.8897347946
495000 --> 119949.74656660156
371000 --> 487675.2055801831
1025000 --> 652062.6044870841
8150000 --> 380093.8104388375
750000 --> 613509.2542212188
600000 --> 380093.8104388375
80000 --> 569289.4932550091
325000 --> 592938.9536070304
1470000 --> 592938.9536070304
350000 --> 380093.8104388375
2800000 --> 633145.4011515022
210000 --> 474691.6518469233
450000 --> 462866.92167091253
1150000 --> 454653.4640906555
210000 --> 626048.1980998606
4500000 --> 539491.1732114621
2750000 --> -45596.47589754849
1975000 --> 474691.6518469233
175000 --> 611177.4174305095
2500000 --> 652062.6044870841
628000 --> 640237.8743110735
600000 --> 403743.27079085895
399000 --> 569289.4932550091
750000 --> 213078.95648682682
750000 --> 451042.19149490184
315000 --> 566924.5472198069
600000 --> 569289.4932550091
100000 --> 635701.9078155557
250000 --> 576384.3313606154
350000 --> 136504.36881301657
780000 --> 545640.0329029877
434000 --> 498341.1121989447
690000 --> 602398.7377478391
555000 --> 530170.9208867304
120000 --> 582533.191052141
500000 --> 521498.66377564415
165000 --> 427392.7311428804
95000 --> 581114.2234310198
550000 --> 344619.6199108053
100000 --> 427392.7311428804
100000 --> 484151.43598773185
500000 --> 498341.1121989447
800000 --> 618953.3599942541
840000 --> 521990.5725509662
490000 --> 555161.3056407114
125000 --> 592938.9536070304
400000 --> 484208.1946925767
1000000 --> 545640.0329029877
530000 --> 616848.5580229242
840000 --> 548004.9789381898
229999 --> 498341.1121989447
40000 --> 545640.0329029877
130000 --> 652062.6044870841
200000 --> 640237.8743110735
120000 --> 635701.9078155557
75000 --> 427392.7311428804
250000 --> 380093.8104388375
100000 --> 609493.5758534456
280000 --> 518242.13308517076
540000 --> 394283.4866500504
700000 --> 531450.3566917747
525000 --> 309145.4293827732
430000 --> 500706.05823414685
65000 --> 380093.8104388375
800000 --> 560756.7679599997
75000 --> 474098.05039208755
210000 --> 628413.1441350627
195000 --> 604763.6837830412
400000 --> 380093.8104388375
170000 --> 592938.9536070304
225000 --> 533815.3027269769
210000 --> 451042.19149490184
240000 --> 602398.7377478391
300000 --> 403743.27079085895
99000 --> 604763.6837830412
620000 --> 474691.6518469233
500000 --> 500706.05823414685
2550000 --> 545640.0329029877
260000 --> 640237.8743110735
550000 --> 434487.5692484868
150000 --> 533224.0662181764
350000 --> 460461.77155311196
320000 --> 451042.19149490184
400000 --> 451042.19149490184
175000 --> 380093.8104388375
120000 --> 451042.19149490184
320000 --> 451042.19149490184
70000 --> 545640.0329029877
810000 --> 190898.12762266595
95000 --> 538793.5141310774
282000 --> 642602.8203462756
80000 --> 436852.51528368896
72000 --> 490418.5429810175
600000 --> 474691.6518469233
640000 --> 226372.3181506981
380000 --> 384823.70250924176
650000 --> 601381.8109527022
150000 --> 628413.1441350627
280000 --> 604763.6837830412
430000 --> 383168.2402846003
800000 --> 498341.1121989447
75000 --> 573823.0948044916
650000 --> 427392.7311428804
390000 --> 525537.9916037694
100000 --> 451042.19149490184
1500000 --> 604763.6837830412
175000 --> 559829.7091142004
434999 --> 604763.6837830412
170000 --> 533815.3027269769
190000 --> 285495.96903075173
250000 --> 380093.8104388375
229999 --> 546056.2634051832
140000 --> 564051.1377870364
600000 --> 652062.6044870841
280000 --> 609403.7079041079
150000 --> 545640.0329029877
650000 --> 320970.15955878387
210000 --> 521990.5725509662
2900000 --> 569289.4932550091
425000 --> 451042.19149490184
265000 --> 498341.1121989447
890000 --> 477056.5978821254
365000 --> 652062.6044870841
350000 --> 616588.413959052
685000 --> 636217.4660512297
940000 --> 486516.38202293403
1000000 --> 474691.6518469233
1150000 --> 564559.6011846048
450000 --> 533815.3027269769
590000 --> 403743.27079085895
800000 --> 510165.8423749554
385000 --> 380093.8104388375
2000000 --> 616848.5580229242
235000 --> 581114.2234310198
640000 --> 581114.2234310198
52000 --> 451042.19149490184
80000 --> 477056.5978821254
140000 --> 640237.8743110735
120000 --> 296138.22618916136
89999 --> 58461.1496513458
180000 --> 508983.36935735436
1500000 --> 261846.5086787303
700000 --> 501309.1194731234
285000 --> 427392.7311428804
390000 --> 545640.0329029877
125000 --> 414276.74043164926
225000 --> 451042.19149490184
175000 --> 649697.658451882
1075000 --> 557464.7630789983
300000 --> 661498.7391675407
700000 --> 451042.19149490184
90000 --> 569289.4932550091
120000 --> 451042.19149490184
220000 --> 261846.5086787303
300000 --> 469961.759776519
180000 --> 536719.4564582051
170000 --> 498341.1121989447
300000 --> 604763.6837830412
1050000 --> 521990.5725509662
300000 --> 569289.4932550091
465000 --> 427392.7311428804
130000 --> 372800.3168662741
434999 --> 462866.92167091253
500000 --> 604763.6837830412
200000 --> 535352.5176498583
625000 --> 652062.6044870841
110000 --> 604763.6837830412
800000 --> 592938.9536070304
490000 --> 555161.3056407114
880000 --> 546056.2634051832
290000 --> 545640.0329029877
115999 --> 558789.1328587115
360000 --> 498341.1121989447
65000 --> 555099.8170437962
685000 --> 598891.5227776343
300000 --> 529085.4106565726
680000 --> 616848.5580229242
1000000 --> 471461.1355628371
100000 --> 285495.96903075173
160000 --> 451042.19149490184
450000 --> 427392.7311428804
600000 --> 403743.27079085895
180000 --> 628413.1441350627
100000 --> 582296.6964486209
120000 --> 474691.6518469233
130000 --> 474691.6518469233
160000 --> 569289.4932550091
860000 --> 474691.6518469233
650000 --> 380093.8104388375
100000 --> 640237.8743110735
282000 --> 526720.4646213704
300000 --> 545640.0329029877
270000 --> 657620.2276698091
550000 --> 474691.6518469233
450000 --> 639031.7518331202
430000 --> 474691.6518469233
350000 --> 427392.7311428804
350000 --> 427392.7311428804
229999 --> 474691.6518469233
110000 --> 545640.0329029877
395000 --> 545640.0329029877
650000 --> 342254.6738756032
350000 --> 498341.1121989447
1400000 --> 451042.19149490184
360000 --> 474691.6518469233
1300000 --> 647086.7580290188
800000 --> 474691.6518469233
229999 --> 569289.4932550091
315000 --> 361174.2421572203
125000 --> 592938.9536070304
700000 --> 498341.1121989447
160000 --> 581114.2234310198
530000 --> 616848.5580229242
624000 --> 498341.1121989447
250000 --> 268413.9638184866
585000 --> 451042.19149490184
500000 --> 498341.1121989447
350000 --> 562194.6551494026
495000 --> 451042.19149490184
500000 --> 427392.7311428804
430000 --> 474691.6518469233
345000 --> 345934.5299063777
500000 --> 652062.6044870841
425000 --> 332794.8897347946
80000 --> 451042.19149490184
106000 --> 576384.3313606154
180000 --> 545640.0329029877
250000 --> 474691.6518469233
350000 --> 370634.02629802894
60000 --> 498341.1121989447
900000 --> 451042.19149490184
700000 --> 380093.8104388375
2000000 --> 474691.6518469233
1000000 --> 639031.7518331202
1375000 --> 498341.1121989447
1800000 --> 519429.33599484223
160000 --> 592938.9536070304
525000 --> 592938.9536070304
850000 --> 380093.8104388375
800000 --> 380093.8104388375
700000 --> 486516.38202293403
800000 --> 616588.413959052
575000 --> 32446.743264122284
350000 --> 555480.5733554637
250000 --> 510941.54467450175
600000 --> 309145.4293827732
370000 --> 328064.9976643903
80000 --> 531450.3566917747
50000 --> 507644.8099014299
900000 --> 380093.8104388375
300000 --> 478522.8644239508
125000 --> 261846.5086787303
490000 --> 661522.3886278927
300000 --> 451042.19149490184
55000 --> 474691.6518469233
350000 --> 498341.1121989447
755000 --> 609493.5758534456
720000 --> 569289.4932550091
229999 --> 521990.5725509662
1100000 --> 309145.4293827732
400000 --> 380093.8104388375
350000 --> 380093.8104388375
159000 --> 526720.4646213704
550000 --> 644967.7663814777
335000 --> 573156.1800225646
185000 --> 285495.96903075173
229999 --> 628413.1441350627
225000 --> 592938.9536070304
250000 --> 529002.6375453405
400000 --> 553900.7894039487
470000 --> 616588.413959052
300000 --> 318605.21352358174
145000 --> 498341.1121989447
100000 --> 637872.9282758712
500000 --> 645776.5779255168
130000 --> 451042.19149490184
240000 --> 545640.0329029877
150000 --> 498341.1121989447
270000 --> 520770.26039680187
400000 --> 628413.1441350627
200000 --> 463399.034528833
550000 --> 564587.9805370272
325000 --> 521990.5725509662
860000 --> 495876.8384302641
600000 --> 380093.8104388375
125000 --> 380093.8104388375
60000 --> 629595.6171526638
300000 --> 380093.8104388375
190000 --> 344619.6199108053
400000 --> 474691.6518469233
260000 --> 555099.8170437962
400000 --> 462866.92167091253
250000 --> 521990.5725509662
600000 --> 604763.6837830412
175000 --> 661522.3886278927
450000 --> 451042.19149490184
350000 --> 501843.5972770791
800000 --> 434487.5692484868
250000 --> 601216.264730238
600000 --> 380093.8104388375
600000 --> 581114.2234310198
130000 --> 427392.7311428804
90000 --> 600021.9669824609
595000 --> 460501.9756357104
190000 --> 540910.1408325833
50000 --> 474691.6518469233
95000 --> 432122.62321328465
1000000 --> 569289.4932550091
220000 --> 654427.5505222862
400000 --> 507800.8963397533
315000 --> 375922.0456327409
1000000 --> 620135.8330118551
500000 --> 595918.7856113852
1600000 --> 143599.20691862307
500000 --> 451042.19149490184
70000 --> 639031.7518331202
105000 --> 510165.8423749554
400000 --> 521990.5725509662
80000 --> 498341.1121989447
300000 --> 592938.9536070304
409999 --> 403743.27079085895
250000 --> 474691.6518469233
250000 --> 540910.1408325833
215000 --> 514895.73444535973
1400000 --> 395229.4650641312
475000 --> 451042.19149490184
475000 --> 516787.69127352146
75000 --> 493611.2201285404
200000 --> 521990.5725509662
575000 --> 616588.413959052
150000 --> 628413.1441350627
850000 --> 474691.6518469233
350000 --> 592938.9536070304
550000 --> 592938.9536070304
330000 --> 403743.27079085895
1044999 --> 521990.5725509662
300000 --> 638270.2392097852
235000 --> 543275.0868677854
120000 --> 640237.8743110735
130000 --> 474691.6518469233
275000 --> 602081.834979122
270000 --> 427392.7311428804
500000 --> 583479.1694662219
400000 --> 451042.19149490184
600000 --> 451042.19149490184
1350000 --> 482422.66043599905
400000 --> 498341.1121989447
220000 --> 625416.7575084616
300000 --> 552734.871008594
250000 --> 607128.6298182433
600000 --> 380093.8104388375
285000 --> 415568.00096686964
350000 --> 467596.81374131684
170000 --> 510165.8423749554
229999 --> 380093.8104388375
500000 --> 474691.6518469233
75000 --> 380093.8104388375
600000 --> 498341.1121989447
220000 --> 536180.248762179
150000 --> 614223.4679238498
65000 --> 498856.6704346188
120000 --> 413203.0549316675
240000 --> 427392.7311428804
390000 --> 380093.8104388375
180000 --> 545640.0329029877
320000 --> 474691.6518469233
310000 --> 605563.0355429396
420000 --> -163843.77765765577
550000 --> 545640.0329029877
550000 --> 616588.413959052
760000 --> 581114.2234310198
43000 --> 498341.1121989447
250000 --> 427392.7311428804
500000 --> 571890.9338937314
380000 --> 427392.7311428804
1850000 --> 569289.4932550091
350000 --> 513240.2722207182
195000 --> 273671.238854741
225000 --> 637399.9390688308
1125000 --> 427392.7311428804
133000 --> 661285.8940243725
200000 --> 403743.27079085895
940000 --> 592938.9536070304
400000 --> 569289.4932550091
120000 --> 496094.4134655027
625000 --> 403743.27079085895
110000 --> 454353.1159441848
490000 --> 640237.8743110735
140000 --> 427392.7311428804
175000 --> 545640.0329029877
90000 --> 521990.5725509662
275000 --> 559713.8267584755
300000 --> 546056.2634051832
270000 --> 581114.2234310198
130000 --> 403743.27079085895
275000 --> 451042.19149490184
352000 --> 545640.0329029877
180000 --> 569289.4932550091
150000 --> 498341.1121989447
300000 --> 451042.19149490184
300000 --> 436852.51528368896
225000 --> 543986.9356243813
600000 --> 545640.0329029877
500000 --> 451042.19149490184
900000 --> 380093.8104388375
600000 --> 521990.5725509662
450000 --> 640237.8743110735
270000 --> 633852.5200160276
310000 --> 540910.1408325833
250000 --> 616588.413959052
700000 --> 493611.2201285404
650000 --> 498341.1121989447
400000 --> 498341.1121989447
425000 --> 498341.1121989447
600000 --> -45596.47589754849
600000 --> 427392.7311428804
300000 --> 348015.6824173556
450000 --> 429480.9784919639
750000 --> 654427.5505222862
325000 --> 616588.413959052
900000 --> 141234.26088342088
180000 --> 285495.96903075173
350000 --> 427392.7311428804
600000 --> 604763.6837830412
900000 --> 441582.4073540933
350000 --> 616588.413959052
280000 --> 569289.4932550091
225000 --> 539491.1732114621
520000 --> 640237.8743110735
509999 --> 652062.6044870841
556000 --> 427392.7311428804
225000 --> 451042.19149490184
325000 --> 604763.6837830412
365000 --> 592938.9536070304
850000 --> 309145.4293827732
350000 --> 592938.9536070304
225000 --> 545640.0329029877
135000 --> 596167.1049450814
140000 --> 462781.78361364524
665000 --> 498341.1121989447
275000 --> 521990.5725509662
2750000 --> 592938.9536070304
484999 --> 640237.8743110735
565000 --> 555099.8170437962
425000 --> 569289.4932550091
925000 --> 474691.6518469233
565000 --> 592052.0988438297
525000 --> 498341.1121989447
1650000 --> 503071.00426934904
295000 --> 611255.4606496711
2050000 --> 569289.4932550091
1475000 --> 380093.8104388375
1100000 --> 592938.9536070304
4400000 --> 581114.2234310198
670000 --> 451042.19149490184
750000 --> 628413.1441350627
760000 --> 451042.19149490184
850000 --> 380093.8104388375
390000 --> 442965.9007846865
450000 --> 427392.7311428804
425000 --> 616588.413959052
770000 --> 143599.20691862307
1150000 --> 498341.1121989447
775000 --> 491750.0075988363
1725000 --> 498341.1121989447
2150000 --> 451042.19149490184
450000 --> 581114.2234310198
3800000 --> 553900.7894039487
1580000 --> 545640.0329029877
4950000 --> 608873.9599922226
535000 --> 451042.19149490184
225000 --> 526947.4994407499
550000 --> 380093.8104388375
670000 --> 521990.5725509662
625000 --> 432122.62321328465
520000 --> 552836.5636881078
239000 --> 564559.6011846048
2600000 --> 566865.4235689269
750000 --> 521990.5725509662
229999 --> 592938.9536070304
1300000 --> 502342.60089050676
80000 --> 548004.9789381898
385000 --> 427392.7311428804
760000 --> 576384.3313606154
600000 --> 247893.3270710376
450000 --> 467596.81374131684
3800000 --> 604763.6837830412
1580000 --> 569289.4932550091
4950000 --> 545640.0329029877
535000 --> 474691.6518469233
225000 --> 593175.4482105507
550000 --> 498341.1121989447
670000 --> 569289.4932550091
625000 --> 569289.4932550091
520000 --> 569289.4932550091
239000 --> 474691.6518469233
2600000 --> 523445.0143626155
750000 --> 521990.5725509662
229999 --> 380093.8104388375
1300000 --> 474691.6518469233
80000 --> 380093.8104388375
385000 --> 576384.3313606154
760000 --> 521990.5725509662
600000 --> 451042.19149490184
450000 --> 567184.6912836791
3800000 --> 474691.6518469233
1580000 --> 427392.7311428804
4950000 --> 569289.4932550091
535000 --> 498341.1121989447
225000 --> 581114.2234310198
550000 --> 498341.1121989447
670000 --> 651589.6152800437
625000 --> 640237.8743110735
520000 --> 484624.4251947723
239000 --> 567466.1198618682
2600000 --> 592938.9536070304
750000 --> 618953.3599942541
229999 --> 427392.7311428804
1300000 --> 380093.8104388375
80000 --> 607128.6298182433
385000 --> 403743.27079085895
760000 --> 604763.6837830412
600000 --> 540910.1408325833
450000 --> 596531.3066345026
3800000 --> 533815.3027269769
1580000 --> 479421.54391732754
4950000 --> 547501.2454326916
535000 --> -45596.47589754849
225000 --> 515680.8965290468
550000 --> 498341.1121989447
670000 --> 592938.9536070304
625000 --> 134943.5044297832
520000 --> 604763.6837830412
239000 --> 614223.4679238498
2600000 --> 427392.7311428804
750000 --> 628413.1441350627
229999 --> 616588.413959052
1300000 --> 552351.7497508912
80000 --> 545640.0329029877
385000 --> 498341.1121989447
760000 --> 403743.27079085895
600000 --> 498341.1121989447
350000 --> 529085.4106565726
114999 --> 451042.19149490184
380000 --> 538545.1947973812
95000 --> 380093.8104388375
900000 --> 571131.7862164315
200999 --> 637872.9282758712
229999 --> 521990.5725509662
800000 --> 498341.1121989447
150000 --> 521990.5725509662
600000 --> 427392.7311428804
150000 --> 474691.6518469233
150000 --> 498341.1121989447
380000 --> 545640.0329029877
80000 --> 628413.1441350627
225000 --> 427392.7311428804
75000 --> 443278.0736613332
1600000 --> 503071.00426934904
185000 --> 498341.1121989447
425000 --> 427392.7311428804
100000 --> 530078.6879913575
140000 --> 623683.2520646583
710000 --> 604763.6837830412
450000 --> 569289.4932550091
210000 --> 498341.1121989447
270000 --> 423019.9459237916
110000 --> 647332.7124166798
540000 --> 451042.19149490184
145000 --> 566628.9289654066
360000 --> 628413.1441350627
250000 --> 451042.19149490184
110000 --> 526720.4646213704
250000 --> 403743.27079085895
150000 --> 406744.38730953046
140000 --> 543275.0868677854
925000 --> 530078.6879913575
969999 --> 602398.7377478391
90000 --> 635507.9822406691
55000 --> 574019.3853254133
155000 --> 530078.6879913575
900000 --> 578749.2773958177
135000 --> 451042.19149490184
180000 --> 521990.5725509662
495000 --> 569289.4932550091
400000 --> 482732.4683666106
250000 --> 624667.0696153025
138000 --> 639031.7518331202
311000 --> 403743.27079085895
190000 --> 403743.27079085895
311000 --> 645204.2609849978
300000 --> 451042.19149490184
600000 --> 604763.6837830412
550000 --> 633143.036205467
600000 --> 434518.3135469444
195000 --> 604763.6837830412
58000 --> 524710.2604914487
183000 --> 533815.3027269769
95000 --> 592938.9536070304

In [10]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [11]:
print(r2_score(y_test,y_pred))

0.04043884538588094

In [12]:
print(mean_absolute_error(y_test,y_pred))

300629.95639712235

In [13]:
print(mean_squared_error(y_test,y_pred))

292829552069.21594

In [14]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [15]:
x = df.drop(['name','selling_price'],axis=1)
y =df['selling_price']

In [16]:
x = pd.get_dummies(x,drop_first=True)
x.head()

,year,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2007,70000,False,False,False,True,True,False,True,False,False,False,False
1,2007,50000,False,False,False,True,True,False,True,False,False,False,False
2,2012,100000,True,False,False,False,True,False,True,False,False,False,False
3,2017,46000,False,False,False,True,True,False,True,False,False,False,False
4,2014,141000,True,False,False,False,True,False,True,False,True,False,False

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred = lr.predict(x_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.4031303601432106
221706.36930930137
182146878750.2813

In [20]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [21]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [22]:
df["brand"] = df['name'].apply(lambda x:x.split()[0])

In [24]:
df['age'] = 2026 - df["year"]

In [26]:
df.drop(['name','year'],axis=1,inplace=True)

In [28]:
df = pd.get_dummies(df,drop_first=True)
df.shape

(4340, 42)

In [39]:
df.head()

,selling_price,km_driven,age,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,...,brand_Mercedes-Benz,brand_Mitsubishi,brand_Nissan,brand_OpelCorsa,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,60000,70000,19,False,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,135000,50000,19,False,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
2,600000,100000,14,True,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
3,250000,46000,9,False,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
4,450000,141000,12,True,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False

In [30]:
x = df.drop('selling_price',axis=1)
y = df['selling_price']

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [33]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=10)
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [35]:
y_pred = model.predict(x_test)
from sklearn.metrics import mean_absolute_error,r2_score

print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

175284.62042686483
0.7084240224003235

In [38]:
r2 = []
for i in range(0,43):
    x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=i)
    model = LinearRegression()
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    r2.append(r2_score(y_test,y_pred))
print(max(r2))
print(r2.index(max(r2)))

0.7559672193277194
25

In [34]:
df.head()

,selling_price,km_driven,age,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,...,brand_Mercedes-Benz,brand_Mitsubishi,brand_Nissan,brand_OpelCorsa,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,60000,70000,19,False,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,135000,50000,19,False,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
2,600000,100000,14,True,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
3,250000,46000,9,False,False,False,True,True,False,True,...,False,False,False,False,False,False,False,False,False,False
4,450000,141000,12,True,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False